apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache
  labels:
    app: ganache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
        - name: ganache
          image: trufflesuite/ganache-cli:latest
          args: ["--deterministic", "-p", "8545", "-h", "0.0.0.0"]
          ports:
            - containerPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: ganache-service
spec:
  selector:
    app: ganache
  ports:
    - port: 8545
      targetPort: 8545
