apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: green-energy-frontend
spec:
  type: LoadBalancer
  selector:
    app: green-energy-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
