apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: green-energy-backend
spec:
  selector:
    app: green-energy-backend
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
